name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify your Node.js version

    # Set CI environment variable to false to prevent warnings being treated as errors
    - name: Set CI=false
      run: echo "CI=false" >> $GITHUB_ENV

    # Install dependencies and suppress warnings
    - name: Install dependencies
      run: npm install --silent

    # Build the app and suppress warnings
    - name: Build the app
      run: npm run build --silent

      # Set the Git identity (user.email and user.name)
    - name: Configure Git user identity
      run: |
        git config --global user.email "yaya.benamary@outlook.com"
        git config --global user.name "yaya7211"


    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Automatically provided by GitHub Actions
